version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - "${LOCAL_PC_MOUNT_DIR}:${IMAGE_TEMP_DIR}"
    tty: true
    restart: always
    networks:
      - bridge
  redis:
    image: redis:latest
    restart: always
    ports:
      - ':${REDIS_PORT}'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - bridge
volumes:
  cache:
    driver: local
networks:
  bridge:
    driver: bridge