version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - tbotconf
      - redis
      - kafka
      - tbotdb
    volumes:
      - "${LOCAL_PC_MOUNT_DIR}:/opt/app/temp/"
    tty: true
    restart: always
#    environment:
#      BOT_PROFILE: kuber
    networks:
      - bridge
  redis:
    image: redis:latest
    restart: always
    ports:
      - ':6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - bridge
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - .env
    ports:
      - '22181:2181'
    networks:
      - bridge
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    networks:
      - bridge
    env_file:
      - .env
  tbotdb:
    image: marolok/telegram_db:1.1.1
    depends_on:
      - tbotconf
      - pgsql
    tty: true
    restart: always
    networks:
      - bridge
      - pgnet
  pgsql:
    image: postgres:14
    restart: always
    env_file:
      - .env
    networks:
      - pgnet
    volumes:
      - "${LOCAL_PC_MOUNT_DIR}/db:/var/lib/postgresql/data"
  tbotconf:
    image: marolok/telegram_conf:1.0.0
    environment:
      GIT_URL: 'git@github.com:user/conf_repo.git'
      PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        *******************************
        -----END RSA PRIVATE KEY-----

    tty: true
    restart: always
    networks:
      - bridge
volumes:
  cache:
    driver: local
networks:
  bridge:
    driver: bridge
  pgnet:
    external: false