version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - kafka
    volumes:
      - "${LOCAL_PC_MOUNT_DIR}:${IMAGE_TEMP_DIR}"
    tty: true
    restart: always
    ports:
      - '8080:8080'
    networks:
      - bridge
  redis:
    image: redis:latest
    restart: always
    ports:
      - ':${REDIS_PORT}'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - bridge
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - .env
    ports:
      - '22181:2181'
    networks:
      - bridge
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    networks:
      - bridge
    env_file:
      - .env
volumes:
  cache:
    driver: local
networks:
  bridge:
    driver: bridge