application:
  group:
    chat:
      id: 0000000000
      textLine: 'Welcome to chat'
  bot:
    token: '1111111111:222222222222222222222222222222222'
    admin:
      id: 1111111111
    directory:
      path: 'D:\Temp'
artemis:
  mode: native
  host: localhost
  port: 61616
  user: developer
  password: developer
jms:
  queue:
    destination: telegram_queue