apiVersion: v1
kind: PersistentVolume
metadata:
  name: tbot-data-pv
spec:
  storageClassName: standard
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/mnt/tbot'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tbot-data-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi