apiVersion: v1
kind: ConfigMap
metadata:
  name: telegram-bot-conf
  labels:
    app: telegram-conf-app-label
    tier: telegram-conf-tier-label
data:
  #   Kafka
  KAFKA_BROKER_ID: '1'
  KAFKA_ZOOKEEPER_CONNECT: 'zk-service:22181'
  KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-service1:9092,PLAINTEXT_HOST://kafka-service:29092'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
  KAFKA_CLEANUP_POLICY: 'compact'
  #   ZooKeeper
  ZOOKEEPER_CLIENT_PORT: '2181'
  ZOOKEEPER_TICK_TIME: '2000'
  #   Telegram DB
  SPRING_CLOUD_CONFIG_SERVER: 'configserver:http://tbotconf:8888'
  POSTGRES_USER: 'tdb'
  POSTGRES_PASSWORD: 'tdb'
  POSTGRES_DB: 'tdb'
  PGDATA: '/var/lib/postgresql/data/pgdata'
  #   Telegram Config
  BOT_PROFILE: kuber
  GIT_URL: 'git@github.com:user/conf_repo.git'
  PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    *******************************
    -----END RSA PRIVATE KEY-----
