# Details for our datasource
spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    #    url: jdbc:postgresql://pgsql-service:5432/tdb
    username: SA
    password: SA
  # Hibernate properties
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: false
      naming:
        implicit-strategy :  org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl