# Details for our datasource
spring:
#  graphql:
#    path: /api/gphql
#    schema:
#      locations: classpath:graphql/**/
#      printer:
#        enabled: true
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: SA
    password: SA
# Hibernate properties
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: false
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

#server:
#  port: 8081
#spring:
#  datasource:
##    url: jdbc:postgresql://192.168.3.3:5432/tdb
#    url: jdbc:postgresql://localhost:8800/tdb
#    username: tdb
#    password: tdb
#  flyway:
#    baselineOnMigrate: true
#    locations: classpath:db/migration
##    enabled: true
#  jpa:
#    database: POSTGRESQL
#    show-sql: false
#    hibernate:
#      ddl-auto: validate
##      ddl-auto: none
#      format_sql: false
#      naming:
#        implicit-strategy :  org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl