server:
  port: 8088
spring:
  application:
    name: telegram-db
  profiles:
    active: local
  config:
    import: 'optional:configserver:http://tbotconf:8888'
  graphql:
    path: /api/gphql
    schema:
      locations: classpath:graphql/**/
      printer:
        enabled: true
