spring:
  profiles:
    active: local
  cloud:
    discovery:
      enabled: false
  application:
    name: telegram-bot
  config:
    import: 'optional:configserver:http://tbotconf:8888'
management:
  endpoint:
    health:
      show-details: always
endpoints:
  health:
    sensitive: false
server:
  port: 8080